/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstudiantesIndexRouteImport } from './routes/estudiantes.index'
import { Route as EstudiantesIdRouteImport } from './routes/estudiantes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesIndexRoute = EstudiantesIndexRouteImport.update({
  id: '/estudiantes/',
  path: '/estudiantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesIdRoute = EstudiantesIdRouteImport.update({
  id: '/estudiantes/$id',
  path: '/estudiantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes/': typeof EstudiantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes': typeof EstudiantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes/': typeof EstudiantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estudiantes/$id' | '/estudiantes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estudiantes/$id' | '/estudiantes'
  id: '__root__' | '/' | '/estudiantes/$id' | '/estudiantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstudiantesIdRoute: typeof EstudiantesIdRoute
  EstudiantesIndexRoute: typeof EstudiantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/': {
      id: '/estudiantes/'
      path: '/estudiantes'
      fullPath: '/estudiantes/'
      preLoaderRoute: typeof EstudiantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/$id': {
      id: '/estudiantes/$id'
      path: '/estudiantes/$id'
      fullPath: '/estudiantes/$id'
      preLoaderRoute: typeof EstudiantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstudiantesIdRoute: EstudiantesIdRoute,
  EstudiantesIndexRoute: EstudiantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
