/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AsistenciaRouteImport } from './routes/asistencia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SaludRouteImport } from './routes/salud'
import { Route as SigeRouteImport } from './routes/sige'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as EstudiantesIndexRouteImport } from './routes/estudiantes.index'
import { Route as EstudiantesIdRouteImport } from './routes/estudiantes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenciaRoute = AsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SaludRoute = SaludRouteImport.update({
  id: '/salud',
  path: '/salud',
  getParentRoute: () => rootRouteImport,
} as any)
const SigeRoute = SigeRouteImport.update({
  id: '/sige',
  path: '/sige',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EstudiantesIndexRoute = EstudiantesIndexRouteImport.update({
  id: '/estudiantes/',
  path: '/estudiantes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesIdRoute = EstudiantesIdRouteImport.update({
  id: '/estudiantes/$id',
  path: '/estudiantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/auth': typeof AuthRoute
  '/salud': typeof SaludRoute
  '/sige': typeof SigeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes/': typeof EstudiantesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistencia': typeof AsistenciaRoute
  '/auth': typeof AuthRoute
  '/salud': typeof SaludRoute
  '/sige': typeof SigeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes': typeof EstudiantesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/asistencia': typeof AsistenciaRoute
  '/auth': typeof AuthRoute
  '/salud': typeof SaludRoute
  '/sige': typeof SigeRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/estudiantes/': typeof EstudiantesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/asistencia'
    | '/auth'
    | '/salud'
    | '/sige'
    | '/admin'
    | '/estudiantes/$id'
    | '/estudiantes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/asistencia'
    | '/auth'
    | '/salud'
    | '/sige'
    | '/admin'
    | '/estudiantes/$id'
    | '/estudiantes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/asistencia'
    | '/auth'
    | '/salud'
    | '/sige'
    | '/_authenticated/admin'
    | '/estudiantes/$id'
    | '/estudiantes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AsistenciaRoute: typeof AsistenciaRoute
  AuthRoute: typeof AuthRoute
  SaludRoute: typeof SaludRoute
  SigeRoute: typeof SigeRoute
  EstudiantesIdRoute: typeof EstudiantesIdRoute
  EstudiantesIndexRoute: typeof EstudiantesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistencia': {
      id: '/asistencia'
      path: '/asistencia'
      fullPath: '/asistencia'
      preLoaderRoute: typeof AsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salud': {
      id: '/salud'
      path: '/salud'
      fullPath: '/salud'
      preLoaderRoute: typeof SaludRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sige': {
      id: '/sige'
      path: '/sige'
      fullPath: '/sige'
      preLoaderRoute: typeof SigeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/estudiantes/': {
      id: '/estudiantes/'
      path: '/estudiantes'
      fullPath: '/estudiantes/'
      preLoaderRoute: typeof EstudiantesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes/$id': {
      id: '/estudiantes/$id'
      path: '/estudiantes/$id'
      fullPath: '/estudiantes/$id'
      preLoaderRoute: typeof EstudiantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AsistenciaRoute: AsistenciaRoute,
  AuthRoute: AuthRoute,
  SaludRoute: SaludRoute,
  SigeRoute: SigeRoute,
  EstudiantesIdRoute: EstudiantesIdRoute,
  EstudiantesIndexRoute: EstudiantesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
